- name: variables
  hosts: local
  connection: local
  tasks:
  - name: print the variable
    ansible.builtin.debug:
      msg: "hello course is devops with aws,duration is 120hrs,trainer is siva kumar reddy"
