- name: variables from inventory
  hosts: local
  connection: local
  tasks:
  - name: getting variables from inventory
    ansible.builtin.debug:
      msg: "course is {{ COURSE }},duration of the course is {{ DURATION }}, 
      Trainer is {{ TRAINER }}"
  