- name: variables from server ip
  hosts: web
  # connection: local
  tasks:
  - name: getting variables from inventory ip addresses
    ansible.builtin.debug:
      msg: "course is {{ COURSE }},DURATION IS {{ DURATION }}, TRAINER IS {{ TRAINER }}"
