- name: datatypes in ansible
  hosts: local
  connection: local
  vars:
    course: "devops with aws" # sting datatype
    duration: 120 # number datatype
    topics: # list data type {}
    - linux
    - shell
    - cloud
    tools: # mapping or map []
     ci: jenkins
     cloud: aws
     container: docker
    live: yes  # boolean
  tasks:
  - name: course details
    ansible.builtin.debug:
      msg: "name of the course is {{ course }},duration in hours {{ duration }},topics covered are {{ topics }},is class live {{ live }},tools used are {{ tools }}"