- name: checking number gretaer or not than 10
  hosts: local
  connection: local
  vars:
    mynum: 20
  tasks:
  - name: checking greater 
    ansible.builtin.debug:
      msg: "given number {{ mynum }} is greaterthan 10"
    when: mynum > 10
  - name: checking lessthan or equal
    ansible.builtin.debug:
      msg: "given number {{ mynum }} is lessthan or equal to 10"
